name: Test File Empty

on:
  push:
    branches:
      - main
      
jobs:
  check-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Read file
        id: current-migration
        uses: juliangruber/read-file-action@v1.1.4
        with:
            path: ./@app/db/migrations/current.sql
      - name: Echo current.sql
        run: echo "${{ steps.current-migration.outputs.content }}"

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v18.6

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

