name: Test File Empty

on:
  push:
    branches:
      - main
      
jobs:
  check-current-sql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Read file
        id: current-migration
        uses: juliangruber/read-file-action@v1.1.4
        with:
            path: ./@app/db/migrations/current.sql
            trim: true
      - name: Check if current.sql is dirty
        if: ${{ steps.current-migration.outputs.content == '-- Enter migration here' }}
        run: echo "Current.sql is clean"
      - name: Fail if current.sql dirty
        if: ${{ steps.current-migration.outputs.content != '-- Enter migration here' }}
        run: exit 1
